name: flutter_frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Map & Location
  flutter_map: ^8.2.2
  flutter_map_location_marker: ^10.1.0
  geolocator: ^14.0.2
  latlong2: ^0.9.1
  geocoding: ^2.1.0
  google_maps_flutter: ^2.2.0
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.0
  shared_preferences: ^2.2.2

  # ML & Sensors - TAMBAHAN BARU
  tflite_flutter: ^0.10.4
  sensors_plus: ^6.0.1
  
  # Others
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  intl: ^0.19.0  # Tambahkan jika belum ada

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/Mask_group.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/BACKGROUND.png
    - assets/icons/Mask_group.png
    - assets/icons/google.png
    - assets/icons/telfon.png
    - assets/icons/lari.png
    - assets/icons/peta.png
    - assets/icons/langkah.png
    - assets/icons/kalori.png
    - assets/icons/body_target.png 
    - assets/icons/logo_kecil.png
    - assets/icons/langkah_kecil.png  
    - assets/icons/durasi_logo.png 
    - assets/icons/lari_logo.png 
    - assets/icons/Trophy.png 
    - assets/icons/Ribbon.png 
    - assets/icons/Party_Popper.png 
    - assets/icons/Confetti_Ball.png 
    # ML Model - TAMBAHAN BARU
    - assets/ml_model/run_walk_model.tflite
    - assets/ml_model/scaler_params.json

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/poppins.bold.ttf
        - asset: assets/fonts/poppins/poppins.regular.ttf